# ── JobRadar config ──────────────────────────────────────────
# Edit these any time. Name, email, location, and target role
# come from profile.json (generated by setup.py).

WORK_TYPE = "any"                       # "remote", "hybrid", "onsite", "any"
EXPERIENCE = "entry"                # "entry", "mid-level", "senior"
MIN_SCORE = 40                          # Match threshold (0–100)
INCLUDE_REMOTE = True                   # Also pull remote jobs from Remotive
INCLUDE_INTERNSHIPS = True              # Also search for internship listings
MAX_RESULTS_PER_SOURCE = 50             # Max listings to fetch per API
MAX_EMAIL_JOBS = 15                     # Max jobs to include in digest

# Adzuna country codes mapped from common location strings
ADZUNA_COUNTRY_MAP = {
    # Countries
    "ireland": "ie", "united kingdom": "gb", "uk": "gb",
    "germany": "de", "france": "fr", "netherlands": "nl",
    "austria": "at", "switzerland": "ch", "poland": "pl",
    "italy": "it", "spain": "es", "belgium": "be",
    "united states": "us", "usa": "us", "us": "us",
    "canada": "ca", "australia": "au", "india": "in",
    "brazil": "br", "singapore": "sg", "south africa": "za",
    "new zealand": "nz", "mexico": "mx", "russia": "ru",
    # Continents → expand to multiple countries
    "europe": ["ie", "gb", "de", "fr", "nl", "at", "ch", "pl", "it", "es", "be"],
    "north america": ["us", "ca"],
    "asia": ["in", "sg"],
    "oceania": ["au", "nz"],
}

# City → country mapping (common cities)
CITY_COUNTRY_MAP = {
    "dublin": "ie", "london": "gb", "berlin": "de", "paris": "fr",
    "amsterdam": "nl", "vienna": "at", "zurich": "ch", "warsaw": "pl",
    "rome": "it", "madrid": "es", "brussels": "be", "lisbon": "pt",
    "new york": "us", "san francisco": "us", "toronto": "ca",
    "sydney": "au", "mumbai": "in", "singapore": "sg",
    "cape town": "za", "auckland": "nz", "mexico city": "mx",
}
